# Generated by Django 5.1.2 on 2025-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
    ]
