# Generated by Django 5.1.2 on 2025-02-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_stamp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.ImageField(default='stamps/default.png', upload_to='stamps/'),
        ),
    ]
