# Generated by Django 5.1.2 on 2025-02-05 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_alter_stamp_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamp',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='price',
        ),
        migrations.AddField(
            model_name='stamp',
            name='shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('rectangle', 'Rectangle'), ('oval', 'Oval'), ('square', 'Square')], default='circle', max_length=20),
        ),
        migrations.AddField(
            model_name='stamp',
            name='text_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stamp',
            name='text_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stamp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, default='stamps/default.png', null=True, upload_to='stamps/'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.TextField()),
                ('qr_code_image', models.ImageField(upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='stamps.stamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
