# Generated by Django 5.1.2 on 2025-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_rename_description_stamp_text_remove_stamp_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='serial_number',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
